definitions:
  github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  github_com_viniciusdsouza_goverallratings_handler_shows.CreateShowResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.ShowResponse'
      message:
        type: string
    type: object
  github_com_viniciusdsouza_goverallratings_handler_shows.DeleteShowResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.ShowResponse'
      message:
        type: string
    type: object
  github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  github_com_viniciusdsouza_goverallratings_handler_shows.GetShowResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.ShowResponse'
      message:
        type: string
    type: object
  github_com_viniciusdsouza_goverallratings_handler_shows.ListShowResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.ShowResponse'
        type: array
      message:
        type: string
    type: object
  github_com_viniciusdsouza_goverallratings_handler_shows.UpdateShowResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.ShowResponse'
      message:
        type: string
    type: object
  handler.CreateBookRequest:
    properties:
      authorName:
        type: string
      genre:
        type: string
      rating:
        type: integer
      title:
        type: string
    type: object
  handler.CreateBookResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.BookResponse'
      message:
        type: string
    type: object
  handler.CreateMovieRequest:
    properties:
      duration:
        type: integer
      genre:
        type: string
      rating:
        type: integer
      title:
        type: string
    type: object
  handler.CreateMovieResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.MovieResponse'
      message:
        type: string
    type: object
  handler.CreateShowRequest:
    properties:
      episodes:
        type: integer
      genre:
        type: string
      rating:
        type: integer
      seasons:
        type: integer
      title:
        type: string
    type: object
  handler.DeleteBookResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.BookResponse'
      message:
        type: string
    type: object
  handler.DeleteMovieResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.MovieResponse'
      message:
        type: string
    type: object
  handler.GetBookResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.BookResponse'
      message:
        type: string
    type: object
  handler.GetMovieResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.MovieResponse'
      message:
        type: string
    type: object
  handler.ListBookResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.BookResponse'
        type: array
      message:
        type: string
    type: object
  handler.ListMovieResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.MovieResponse'
        type: array
      message:
        type: string
    type: object
  handler.UpdateBookRequest:
    properties:
      authorName:
        type: string
      genre:
        type: string
      rating:
        type: integer
      title:
        type: string
    type: object
  handler.UpdateBookResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.BookResponse'
      message:
        type: string
    type: object
  handler.UpdateMovieRequest:
    properties:
      duration:
        type: integer
      genre:
        type: string
      rating:
        type: integer
      title:
        type: string
    type: object
  handler.UpdateMovieResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.MovieResponse'
      message:
        type: string
    type: object
  handler.UpdateShowRequest:
    properties:
      episodes:
        type: integer
      genre:
        type: string
      rating:
        type: integer
      seasons:
        type: integer
      title:
        type: string
    type: object
  schemas.BookResponse:
    properties:
      authorName:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      genre:
        type: string
      id:
        type: integer
      rating:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
    type: object
  schemas.MovieResponse:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      duration:
        type: integer
      genre:
        type: string
      id:
        type: integer
      rating:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
    type: object
  schemas.ShowResponse:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      episodes:
        type: integer
      genre:
        type: string
      id:
        type: integer
      rating:
        type: integer
      seasons:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /books:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListBookResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
      summary: List books
      tags:
      - Books
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CreateBookResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
      summary: Create book
      tags:
      - Books
  /books/:id:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DeleteBookResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
      summary: Delete book
      tags:
      - Books
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetBookResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
      summary: Get book
      tags:
      - Books
    put:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UpdateBookResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_books.ErrorResponse'
      summary: Update book
      tags:
      - Books
  /movies:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListMovieResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
      summary: List movies
      tags:
      - Movies
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateMovieRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CreateMovieResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
      summary: Create movie
      tags:
      - Movies
  /movies/:id:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DeleteMovieResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
      summary: Delete movie
      tags:
      - Movies
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetMovieResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
      summary: Get movie
      tags:
      - Movies
    put:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateMovieRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UpdateMovieResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_movies.ErrorResponse'
      summary: Update movie
      tags:
      - Movies
  /shows:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ListShowResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
      summary: List shows
      tags:
      - Shows
    post:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateShowRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.CreateShowResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
      summary: Create show
      tags:
      - Shows
  /shows/:id:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.DeleteShowResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
      summary: Delete show
      tags:
      - Shows
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.GetShowResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
      summary: Get show
      tags:
      - Shows
    put:
      consumes:
      - application/json
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateShowRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.UpdateShowResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_viniciusdsouza_goverallratings_handler_shows.ErrorResponse'
      summary: Update show
      tags:
      - Shows
swagger: "2.0"
